import os

# 1. Updated React App with Multi-Role Login, Notifications, Uploader, Doctor, Admin & Patient Views
app_tsx_content = """import React, { useState } from 'react'
import { 
  Cpu, Activity, CheckCircle, AlertTriangle, Clock, Bell, User, Lock, 
  FileText, Upload, ShieldCheck, LogOut, FileUp, CheckSquare, Stethoscope, Search, Download, QrCode 
} from 'lucide-react'

type Role = 'ADMIN' | 'DOCTOR' | 'LAB_STAFF' | 'PATIENT'

interface NotificationItem {
  id: number
  title: string
  message: string
  time: string
  unread: boolean
}

export default function App() {
  const [user, setUser] = useState<{ name: string; role: Role; email: string } | null>(null)
  const [notifications, setNotifications] = useState<NotificationItem[]>([
    { id: 1, title: "Report Ready", message: "CBC Report #RPT-2026-001245 generated by C++ Engine", time: "2m ago", unread: true },
    { id: 2, title: "SMS Sent", message: "Notification SMS delivered to Rahul Sharma (+91 98765-43210)", time: "5m ago", unread: true },
    { id: 3, title: "Doctor Notification", message: "Dr. Patel reviewed HbA1c test results", time: "12m ago", unread: false }
  ])
  const [showNotifications, setShowNotifications] = useState(false)

  // Login Pre-fill Handler
  const handleDemoLogin = (role: Role) => {
    if (role === 'ADMIN') setUser({ name: 'System Admin', role: 'ADMIN', email: 'admin@medflow.org' })
    if (role === 'DOCTOR') setUser({ name: 'Dr. Rajesh Patel', role: 'DOCTOR', email: 'dr.patel@medflow.org' })
    if (role === 'LAB_STAFF') setUser({ name: 'Suresh Kumar (Lab Tech)', role: 'LAB_STAFF', email: 'uploader@medflow.org' })
    if (role === 'PATIENT') setUser({ name: 'Rahul Sharma', role: 'PATIENT', email: 'rahul.sharma@gmail.com' })
  }

  const unreadCount = notifications.filter(n => n.unread).length

  // 1. LOGIN SCREEN
  if (!user) {
    return (
      <div className="min-h-screen bg-slate-950 text-slate-100 flex items-center justify-center p-4 font-sans">
        <div className="max-w-md w-full bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl">
          <div className="text-center mb-8">
            <div className="inline-flex p-3 bg-sky-950 border border-sky-800 rounded-xl mb-3 text-sky-400">
              <Cpu className="w-8 h-8 animate-pulse" />
            </div>
            <h1 className="text-2xl font-bold tracking-tight text-white">MedFlow Portal</h1>
            <p className="text-xs text-slate-400 mt-1">Diagnostic Management & C++ Parallel Processing Platform</p>
          </div>

          <div className="space-y-4 mb-8">
            <p className="text-xs font-semibold text-slate-400 uppercase tracking-wider text-center">Select Role to Sign In</p>
            <div className="grid grid-cols-2 gap-3">
              <button onClick={() => handleDemoLogin('ADMIN')} className="p-3 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-xl text-left transition">
                <ShieldCheck className="w-5 h-5 text-sky-400 mb-1" />
                <p className="text-sm font-bold">Super Admin</p>
                <p className="text-[10px] text-slate-400">System & Thread Pool</p>
              </button>

              <button onClick={() => handleDemoLogin('LAB_STAFF')} className="p-3 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-xl text-left transition">
                <FileUp className="w-5 h-5 text-emerald-400 mb-1" />
                <p className="text-sm font-bold">Report Uploader</p>
                <p className="text-[10px] text-slate-400">Lab Data & Orders</p>
              </button>

              <button onClick={() => handleDemoLogin('DOCTOR')} className="p-3 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-xl text-left transition">
                <Stethoscope className="w-5 h-5 text-indigo-400 mb-1" />
                <p className="text-sm font-bold">Doctor</p>
                <p className="text-[10px] text-slate-400">Review & Patients</p>
              </button>

              <button onClick={() => handleDemoLogin('PATIENT')} className="p-3 bg-slate-800 hover:bg-slate-700 border border-slate-700 rounded-xl text-left transition">
                <User className="w-5 h-5 text-amber-400 mb-1" />
                <p className="text-sm font-bold">Customer / Patient</p>
                <p className="text-[10px] text-slate-400">View PDF & Verification</p>
              </button>
            </div>
          </div>

          <form onSubmit={(e) => { e.preventDefault(); handleDemoLogin('ADMIN'); }} className="space-y-4 border-t border-slate-800 pt-6">
            <div>
              <label className="text-xs text-slate-400">User Email</label>
              <div className="relative mt-1">
                <User className="w-4 h-4 absolute left-3 top-3 text-slate-500" />
                <input type="email" defaultValue="admin@medflow.org" className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-9 pr-3 py-2 text-sm text-slate-200 focus:border-sky-500 outline-none" />
              </div>
            </div>
            <div>
              <label className="text-xs text-slate-400">Password</label>
              <div className="relative mt-1">
                <Lock className="w-4 h-4 absolute left-3 top-3 text-slate-500" />
                <input type="password" defaultValue="••••••••" className="w-full bg-slate-950 border border-slate-800 rounded-lg pl-9 pr-3 py-2 text-sm text-slate-200 focus:border-sky-500 outline-none" />
              </div>
            </div>
            <button type="submit" className="w-full bg-sky-600 hover:bg-sky-500 text-white font-semibold py-2.5 rounded-lg transition text-sm">
              Sign In
            </button>
          </form>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6 font-sans">
      {/* HEADER WITH USER & NOTIFICATIONS */}
      <header className="max-w-7xl mx-auto flex justify-between items-center mb-8 border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2 bg-sky-950 border border-sky-800 rounded-xl text-sky-400">
            <Cpu className="w-6 h-6 animate-pulse" />
          </div>
          <div>
            <h1 className="text-xl font-bold tracking-tight text-sky-400">MedFlow Platform</h1>
            <p className="text-xs text-slate-400">Role: <span className="font-semibold text-emerald-400">{user.role}</span> | {user.name}</p>
          </div>
        </div>

        <div className="flex items-center gap-4">
          {/* NOTIFICATION BELL */}
          <div className="relative">
            <button 
              onClick={() => setShowNotifications(!showNotifications)}
              className="p-2.5 bg-slate-900 border border-slate-800 rounded-xl text-slate-300 hover:text-white relative transition"
            >
              <Bell className="w-5 h-5" />
              {unreadCount > 0 && (
                <span className="absolute -top-1 -right-1 bg-rose-500 text-white text-[10px] font-bold w-4 h-4 rounded-full flex items-center justify-center">
                  {unreadCount}
                </span>
              )}
            </button>

            {/* NOTIFICATION DROPDOWN PANEL */}
            {showNotifications && (
              <div className="absolute right-0 mt-2 w-80 bg-slate-900 border border-slate-800 rounded-xl shadow-2xl p-4 z-50">
                <div className="flex justify-between items-center mb-3 pb-2 border-b border-slate-800">
                  <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">Notifications Center</h3>
                  <button onClick={() => setNotifications(notifications.map(n => ({...n, unread: false})))} className="text-[10px] text-sky-400 hover:underline">
                    Mark all as read
                  </button>
                </div>
                <div className="space-y-2">
                  {notifications.map(n => (
                    <div key={n.id} className={`p-2.5 rounded-lg border ${n.unread ? 'bg-slate-800/80 border-sky-500/50' : 'bg-slate-950/40 border-slate-800'}`}>
                      <div className="flex justify-between items-start">
                        <p className="text-xs font-bold text-sky-300">{n.title}</p>
                        <span className="text-[10px] text-slate-500">{n.time}</span>
                      </div>
                      <p className="text-xs text-slate-400 mt-1">{n.message}</p>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          <button onClick={() => setUser(null)} className="flex items-center gap-2 bg-slate-900 hover:bg-slate-800 border border-slate-800 px-3 py-2 rounded-xl text-xs font-medium text-rose-400 transition">
            <LogOut className="w-4 h-4" /> Sign Out
          </button>
        </div>
      </header>

      {/* DASHBOARDS BY ROLE */}
      <main className="max-w-7xl mx-auto">
        {/* 1. SUPER ADMIN DASHBOARD */}
        {user.role === 'ADMIN' && (
          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl">
              <h2 className="text-lg font-bold text-sky-400 mb-4 flex items-center gap-2">
                <Cpu className="w-5 h-5 text-sky-400" /> C++ Native Thread Pool Real-Time Metrics
              </h2>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-6">
                <div className="bg-slate-800/60 p-4 rounded-lg border border-slate-700/50">
                  <span className="text-xs text-slate-400">Queue Size</span>
                  <p className="text-2xl font-black text-amber-400 mt-1">12</p>
                </div>
                <div className="bg-slate-800/60 p-4 rounded-lg border border-slate-700/50">
                  <span className="text-xs text-slate-400">Total Completed Jobs</span>
                  <p className="text-2xl font-black text-emerald-400 mt-1">1,482</p>
                </div>
                <div className="bg-slate-800/60 p-4 rounded-lg border border-slate-700/50">
                  <span className="text-xs text-slate-400">Avg Execution Time</span>
                  <p className="text-2xl font-black text-sky-400 mt-1">1.2 ms</p>
                </div>
                <div className="bg-slate-800/60 p-4 rounded-lg border border-slate-700/50">
                  <span className="text-xs text-slate-400">Active Workers</span>
                  <p className="text-2xl font-black text-indigo-400 mt-1">3 / 8</p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* 2. LAB STAFF / REPORT UPLOADER DASHBOARD */}
        {user.role === 'LAB_STAFF' && (
          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl">
              <h2 className="text-lg font-bold text-emerald-400 mb-2 flex items-center gap-2">
                <FileUp className="w-5 h-5 text-emerald-400" /> Diagnostic Test Data Entry & Report Uploader
              </h2>
              <p className="text-xs text-slate-400 mb-6">Enter patient test parameters or upload test files to trigger C++ parallel processing.</p>

              <form onSubmit={(e) => { e.preventDefault(); alert('Test submitted to C++ Thread Pool processing queue!'); }} className="space-y-4 max-w-xl">
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-xs text-slate-400">Patient ID</label>
                    <input type="text" defaultValue="PAT-2026-00124" className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-xs mt-1 text-slate-200" />
                  </div>
                  <div>
                    <label className="text-xs text-slate-400">Test Category</label>
                    <select className="w-full bg-slate-950 border border-slate-800 rounded-lg p-2.5 text-xs mt-1 text-slate-200">
                      <option>CBC (Complete Blood Count)</option>
                      <option>Lipid Profile</option>
                      <option>HbA1c</option>
                    </select>
                  </div>
                </div>

                <div className="grid grid-cols-3 gap-3 bg-slate-950 p-4 rounded-lg border border-slate-800">
                  <div>
                    <label className="text-[10px] text-slate-400">Hemoglobin (g/dL)</label>
                    <input type="text" defaultValue="14.2" className="w-full bg-slate-900 border border-slate-800 rounded p-2 text-xs mt-1 text-emerald-400 font-mono" />
                  </div>
                  <div>
                    <label className="text-[10px] text-slate-400">WBC (/µL)</label>
                    <input type="text" defaultValue="7,200" className="w-full bg-slate-900 border border-slate-800 rounded p-2 text-xs mt-1 text-emerald-400 font-mono" />
                  </div>
                  <div>
                    <label className="text-[10px] text-slate-400">Platelets (/µL)</label>
                    <input type="text" defaultValue="2,45,000" className="w-full bg-slate-900 border border-slate-800 rounded p-2 text-xs mt-1 text-emerald-400 font-mono" />
                  </div>
                </div>

                <div className="border-2 border-dashed border-slate-800 rounded-xl p-6 text-center hover:border-slate-700 transition cursor-pointer">
                  <Upload className="w-8 h-8 mx-auto text-slate-500 mb-2" />
                  <p className="text-xs text-slate-300 font-semibold">Click to upload raw analyzer CSV / XML files</p>
                  <p className="text-[10px] text-slate-500 mt-1">Supports auto-batch parallel report generation</p>
                </div>

                <button type="submit" className="bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-semibold px-5 py-2.5 rounded-lg transition">
                  Generate Parallel Report (C++ Queue)
                </button>
              </form>
            </div>
          </div>
        )}

        {/* 3. DOCTOR DASHBOARD */}
        {user.role === 'DOCTOR' && (
          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl">
              <h2 className="text-lg font-bold text-indigo-400 mb-4 flex items-center gap-2">
                <Stethoscope className="w-5 h-5 text-indigo-400" /> Assigned Patient Reports & Reviews
              </h2>
              <div className="space-y-3">
                {[
                  { name: "Rahul Sharma", id: "PAT-00124", test: "CBC", flag: "NORMAL", time: "10m ago" },
                  { name: "Ananya Roy", id: "PAT-00128", test: "Lipid Profile", flag: "HIGH CHOLESTEROL", time: "1h ago" },
                  { name: "Vikram Singh", id: "PAT-00135", test: "HbA1c", flag: "NORMAL", time: "3h ago" }
                ].map((p, i) => (
                  <div key={i} className="flex justify-between items-center p-4 bg-slate-950 rounded-lg border border-slate-800">
                    <div>
                      <p className="text-sm font-bold text-white">{p.name} <span className="text-xs text-slate-500">({p.id})</span></p>
                      <p className="text-xs text-slate-400 mt-0.5">Test: {p.test} | Generated {p.time}</p>
                    </div>
                    <div className="flex items-center gap-3">
                      <span className={`text-[10px] font-bold px-2.5 py-1 rounded-full ${p.flag === 'NORMAL' ? 'bg-emerald-950 text-emerald-400 border border-emerald-800' : 'bg-rose-950 text-rose-400 border border-rose-800'}`}>
                        {p.flag}
                      </span>
                      <button className="text-xs bg-indigo-950 border border-indigo-800 text-indigo-300 hover:bg-indigo-900 px-3 py-1.5 rounded-lg transition">
                        Review Report
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* 4. CUSTOMER / PATIENT DASHBOARD */}
        {user.role === 'PATIENT' && (
          <div className="space-y-6">
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-6 shadow-xl">
              <h2 className="text-lg font-bold text-amber-400 mb-4 flex items-center gap-2">
                <User className="w-5 h-5 text-amber-400" /> Patient Medical Reports & Downloads
              </h2>
              <div className="space-y-3">
                {[
                  { title: "Complete Blood Count (CBC)", date: "Aug 09, 2026", code: "RPT-2026-001245", status: "READY" },
                  { title: "Lipid Profile", date: "Jul 22, 2026", code: "RPT-2026-000842", status: "READY" }
                ].map((r, i) => (
                  <div key={i} className="flex justify-between items-center p-4 bg-slate-950 rounded-lg border border-slate-800">
                    <div>
                      <p className="text-sm font-bold text-white">{r.title}</p>
                      <p className="text-xs text-slate-400 mt-0.5">Report ID: {r.code} | Date: {r.date}</p>
                    </div>
                    <div className="flex items-center gap-3">
                      <button onClick={() => alert(`Downloading verified PDF for ${r.code}...`)} className="flex items-center gap-1.5 text-xs bg-amber-500/10 border border-amber-500/30 text-amber-400 hover:bg-amber-500/20 px-3 py-2 rounded-lg transition font-semibold">
                        <Download className="w-3.5 h-3.5" /> Download PDF
                      </button>
                      <button onClick={() => alert(`QR Verification Active for Token: ${r.code}`)} className="flex items-center gap-1.5 text-xs bg-slate-800 border border-slate-700 text-slate-300 hover:bg-slate-700 px-3 py-2 rounded-lg transition">
                        <QrCode className="w-3.5 h-3.5" /> Verify
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </main>
    </div>
  )
}
"""

with open("frontend/src/App.tsx", "w", encoding="utf-8") as f:
    f.write(app_tsx_content)

print("App.tsx updated successfully with Multi-Role Login & Notifications!")